export enum DocumentType {
  NATIONAL_ID = 'NATIONAL_ID',
  PROOF_OF_RESIDENCE = 'PROOF_OF_RESIDENCE',
  SELFIE = 'SELFIE',
  DRIVER_LICENSE = 'DRIVER_LICENSE',
  VEHICLE_DOCUMENT = 'VEHICLE_DOCUMENT',
}

